### ISSUE TITLE
Python error when starting spotweb container

### ISSUE THREAD

**Issue by ChaosD** [edv/docker-spotweb#5]
# Environment
rpi3 with 
- docker 17.05.0-ce
- docker-compose version 1.14.0, build c7bdf9e

# Description
I followed your instructions and after building everything, the sportweb container crashed with the following error message: **TypeError: expected string or buffer**

# Logs
```
$ docker-compose -f docker-compose-arm.yml up --build
Building spotweb
Step 1/12 : FROM hypriot/rpi-alpine:3.6
 ---> c5a8d1077f75
Step 2/12 : MAINTAINER Erik de Vries <docker@erikdevries.nl>
 ---> Using cache
 ---> 42125760f776
Step 3/12 : RUN apk -U update &&     apk -U upgrade &&     apk -U add         git         nginx         php5         php5-fpm         php5-curl         php5-dom         php5-gettext         php5-xml         php5-zip         php5-zlib         php5-gd         php5-openssl         php5-mysqli         php5-pdo         php5-pdo_mysql         php5-json         supervisor     &&     git clone --depth 1 https://github.com/spotweb/spotweb.git /var/www/spotweb &&     chown -R nobody:nobody /var/www/spotweb &&     sed -i "s/date.timezone = UTC/date.timezone = \"Europe\/Amsterdam\"/g" /etc/php5/php.ini &&     rm -rf /tmp/src &&     rm -rf /var/cache/apk/*
 ---> Using cache
 ---> ff96fe8df7c7
Step 4/12 : VOLUME /config /nzb
 ---> Using cache
 ---> a97d6be78ff7
Step 5/12 : COPY ./conf/cron/spotweb /etc/periodic/hourly/spotweb
 ---> Using cache
 ---> b080c7af8872
Step 6/12 : RUN chmod +x /etc/periodic/hourly/spotweb
 ---> Using cache
 ---> bae5a3077edf
Step 7/12 : COPY ./conf/supervisord.conf /etc/supervisord.conf
 ---> Using cache
 ---> 2343dd9962a2
Step 8/12 : COPY ./conf/nginx /etc/nginx
 ---> Using cache
 ---> b5dce800f971
Step 9/12 : COPY ./conf/spotweb /var/www/spotweb
 ---> Using cache
 ---> cdf90aa6ebf0
Step 10/12 : COPY ./entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> c94f5dde117b
Step 11/12 : EXPOSE 80
 ---> Using cache
 ---> 0f8154b87a56
Step 12/12 : ENTRYPOINT /bin/sh /entrypoint.sh
 ---> Using cache
 ---> ea68c8388ccb
Successfully built ea68c8388ccb
Successfully tagged dockerspotweb_spotweb:latest
Starting dockerspotweb_mysql_1 ...
Starting dockerspotweb_mysql_1 ... done

ERROR: for spotweb  expected string or buffer
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 118, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 926, in up
    scale_override=parse_scale_args(options['--scale']),
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 424, in up
    get_deps
  File "/usr/local/lib/python2.7/dist-packages/compose/parallel.py", line 69, in parallel_execute
    raise error_to_reraise
TypeError: expected string or buffer
```

I hope the logs help. @edv , it would be nice if you could take a look at this.

//Update: added docker-compose version

**Comment by ChaosD** [comment]
Nevermind, turns out my docker version in pip was outdated. Worked after updating it to 2.4.2.

**Comment by edv** [comment]
Sorry for the late reply, but good to know the problem is solved.
